### ISSUE TITLE
Reason for clearing CFLAGS poorly documented

### ISSUE THREAD

**Issue by Vaelatern** [cmusatyalab/coda#16]
In `lib-src/rpc2/rp2gen/Makefile.am` there is a block of code from commit https://github.com/cmusatyalab/coda/commit/b7ca288894ce442e2dad59f99632517ba0ec232e that goes thus:

```
# override any cross compilation target flags
CFLAGS=-Wall
LDFLAGS=
LIBS=
```

The problem is that my build system tries to build everything with position independent binaries (referred to often as building with PIE) to try and increase security. The clearing of CFLAGS in this manner is thus breaking my assertion that all binaries build are position independent.

I just would like to know what the problem is with having any cross compilation target flags in this build, as I would not want to build coda locally without keeping that in mind.

**Comment by jaharkes** [comment]
rp2gen needs to run on the build machine to generate the rpc2 stub code.

**Comment by Vaelatern** [comment]
Thank you! Isn't it also needed by the final installation of coda, on the target machine?

**Comment by jaharkes** [comment]
If you treat rpc2 as a standalone library, then yes it would be part of a -devel style package that also contains the headers and static libraries. But in the context of Coda, nothing at runtime needs the rp2gen binary, it is only used during the build, so it doesn't need to get installed on the target machine.

**Comment by Vaelatern** [comment]
Thank you so much! Are there perhaps any other binaries that are only needed for build time?

**Comment by jaharkes** [comment]
That should be the only build-time specific one, there are some obscure binaries that get installed that I've personally never used that I'm not even sure if they still do anything useful, like printvrdb, xfrepair, xaskuser, parser, and inoder.

**Comment by Vaelatern** [comment]
Thank you for your help
