### ISSUE TITLE
/usr/sbin/coda-client-setup on Ubuntu 16.04 has syntax error

### ISSUE THREAD

**Issue by krichter722** [cmusatyalab/coda#17]
The `/usr/sbin/coda-client-setup` script which is provided by `.deb` package on Ubuntu 16.04 has the content

    -e #!/bin/sh
    set -e
    echo "Starting \"dpkg-reconfigure coda-client\""
    dpkg-reconfigure coda-client

which makes the script run, but causes a warning for the syntax error.

experienced with 6.9.9-1+ubuntu16.04

**Comment by jaharkes** [comment]
Ah, cool. That is because whatever shell was used during the debian/ubuntu package build was using an internal 'echo' implementation that did not understand the `-e` flag. I'm going to try to replace it with `/bin/echo` and see if that fixes it.
