### ISSUE TITLE
enhance codasrv error message "Fatal: unable to map server-id 1 to host [host], as it is already assigned to host [host]"

### ISSUE THREAD

**Issue by krichter722** [cmusatyalab/coda#24]
`/usr/sbin/startserver` fails due to

    Date: Tue 11/29/2016

    02:23:46 Coda Vice, version 6.9.10      log started at Tue Nov 29 02:23:46 2016

    02:23:46 Fatal: unable to map server-id 1 to host richtercloud.de,
        as it is already assigned to host richtercloud.de

logged to `/vice/srv/SrvLog`. The message doesn't make a lot of sense for an average user and should contain information where parameters (server-id, etc.) are retrieved from and it would be nice if it'd contain hints how to fix that.

I don't overcome this message even after throwing away my setup and running `vice-setup` again (`vice-setup` might return successfully or not (as described in #23)). Specifying another server-id in `vice-setup` doesn't seem to help.

experienced with 6.10.0-1+ubuntu16.10 on Ubuntu 16.10

**Comment by jaharkes** [comment]
Not sure where that error is coming from, I almost think it is duplicate entries in /vice/db/servers, but that wouldn't explain why it still fails after you threw away the old setup.

**Comment by krichter722** [comment]
There's confusion about the `/vice` directory configured in `vice-setup` (in the question `What is the root directory for your coda server(s)? [/vice]` I always choose `/coda-vice` in order to avoid confusion with OpenAFS which also has a `vice` directory (not necessarily `/vice` afaik, but it's still worth paying attention to). After configuring `/coda-vice` the start of `systemd` unit `coda-server` fails due to `systemd[1]: coda-server.service: PID file /vice/srv/pid not readable (yet?) after start: No such file or directory`. That's not right, right?

**Comment by krichter722** [comment]
I just see that `/etc/coda/server.conf` isn't created by `vice-setup` although it runs through. It definitely should, right?
