### ISSUE TITLE
Provide packages for Ubuntu 17.04

### ISSUE THREAD

**Issue by krichter722** [cmusatyalab/coda#32]
It'd be nice to have packages for Ubuntu 17.04/zesty.

**Comment by jaharkes** [comment]
Like this here? http://coda.cs.cmu.edu/coda/dists/zesty/

**Comment by jaharkes** [comment]
Ah, looks like the dists files were created but the pool files are missing.

**Comment by jaharkes** [comment]
We should be good to go now.
