### ISSUE TITLE
Automatically create missing /coda directory

### ISSUE THREAD

**Issue by krichter722** [cmusatyalab/coda#8]
I'm not sure which program mounts `/coda`, but `venus` (one of it's child processes to be precise) fails if the directory doesn't exist. It'd be nice if the directory would be created automatically (by `venus` or the child process) since there should be no disadvantage in that.

experienced with 6.9.6-2+ubuntu16.04 on Ubuntu 16.04

**Comment by jaharkes** [comment]
It is created by either the package installation on debian/ubuntu, or venus-setup when building from source.

**Comment by jaharkes** [comment]
The reason we don't automatically create various directories, but include them as part of the packaging (both deb and rpm) is that they get cleaned up by the package manager when the package is uninstalled.
