### ISSUE TITLE
Whitespace in hostname disturbes vice-setup

### ISSUE THREAD

**Issue by aytchell** [cmusatyalab/coda#98]
This issue is probably related to #13 but since its more specific I'll open an extra ticket.

I encountered some problems getting a server and a client to work with each other. While investigating this I found a spurious space character added to the server's hostname by createvol_rep (see screenshot below: what looks like an indentation is actually part of the given argument)

![vice-setup_fails](https://user-images.githubusercontent.com/19838454/58084144-a4c4b880-7bba-11e9-9984-800e293a5c3a.png)

I've prepared two possible fixes (which might also be combined):
 * the obvious fix is to tell 'createvol_rep' to skip the space. This is [committed](https://github.com/aytchell/coda/commit/efd8483e6d87c1b9d1b7a1884cfd992af0e40944) in my branch [whitespace_1](https://github.com/aytchell/coda/commits/whitespace_1)
 * the "broader" fix is to tell 'volutil' to strip this space from a given hostname argument. This is [committed](https://github.com/aytchell/coda/commit/e3a6dccb95f5bc419660ce40c9ce6cd8d247e2e3) in my branch [whitespace_2](https://github.com/aytchell/coda/tree/whitespace_2).

The second commit is a bit "more invasive" but I think it's a safe thing to do which also helps if there are other scripts injecting malformed arguments.

**Comment by aytchell** [comment]
While writing this I noticed that I did not strip possible trailing spaces. So if you'd like to pull the second commit I could also add code to strip trailing spaces.

**Comment by jaharkes** [comment]
I think I prefer patch 1, simply because volutil -h expects a single server so calling it with "$SERVERS" is wrong anyway if there was more than one server and there should never be whitespace in a hostname. I took the liberty of creating a pull request for your whitespace_1 branch

**Comment by jaharkes** [comment]
Closed by PR #99
